name: run-jmeter

on:
  push:
    branches:
      - main

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Run JMeter test
        run: |
          mkdir -p results
          jmeter -n -t testplan.jmx -l results/result.jtl

      - name: Upload JMeter result
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: results/result.jtl
